spring:
  #redis配置
  redis:
    host: 47.100.85.66
    port: 6379
    password: w1999g1117x
    connect-timeout: 15000
    lettuce:
      pool:
        max-active: 8
        max-wait: 15000
        max-idle: 10
        min-idle: 0